// GENERATED by scripts/gen_tables.py from llama.cpp ggml/src/ggml-common.h (MIT, see NOTICE). Do not edit by hand.
#define GG_HAVE_kmask_iq2xs 1
constant uint8_t kmask_iq2xs[8] = {
    1, 2, 4, 8, 16, 32, 64, 128,
};
