// GENERATED by scripts/gen_tables.py from llama.cpp ggml/src/ggml-common.h (MIT, see NOTICE). Do not edit by hand.
#define GG_HAVE_kvalues_iq4nl 1
constant int8_t kvalues_iq4nl[16] = {
    -127, -104, -83, -65, -49, -35, -22, -10,
    1, 13, 25, 38, 53, 69, 89, 113,
};
