#!/usr/bin/env python3
"""Generates src/iq_tables.zig and src/metal/iq_tables.h from ggml-common.h.

usage: scripts/gen_tables.py path/to/llama.cpp/ggml/src/ggml-common.h
"""
import re
import sys
from pathlib import Path

# name -> (zig type, metal type)
WANT = {
    "kmask_iq2xs": ("u8", "uint8_t"),
    "ksigns_iq2xs": ("u8", "uint8_t"),
    "iq2xxs_grid": ("u64", "uint64_t"),
    "iq2xs_grid": ("u64", "uint64_t"),
    "iq2s_grid": ("u64", "uint64_t"),
    "iq3xxs_grid": ("u32", "uint32_t"),
    "iq3s_grid": ("u32", "uint32_t"),
    "kvalues_iq4nl": ("i8", "int8_t"),
    # ggml's GPU form of the IQ1 grid: 8 weights per entry, a nibble each, value = nibble - 1.
    "iq1s_grid_gpu": ("u32", "uint32_t"),
}
NOTE = "GENERATED by scripts/gen_tables.py from llama.cpp ggml/src/ggml-common.h (MIT, see NOTICE). Do not edit by hand."

src = Path(sys.argv[1]).read_text()
root = Path(__file__).resolve().parent.parent
zig = [f"//! Codebooks for the ggml IQ quant formats.\n//! {NOTE}\n\n// zig fmt: off"]
metal = [f"// Codebooks for the ggml IQ quant formats.\n// {NOTE}\n"]
for name, (zig_ty, metal_ty) in WANT.items():
    m = re.search(r"GGML_TABLE_BEGIN\(\w+, " + name + r", (\w+)\)(.*?)GGML_TABLE_END\(\)", src, re.S)
    vals = re.findall(r"-?0x[0-9a-fA-F]+|-?\d+", m.group(2))
    size = m.group(1)
    if not size.isdigit():
        size = re.search(r"#define " + size + r" (\d+)", src).group(1)
    assert len(vals) == int(size), (name, len(vals))
    per = 4 if zig_ty == "u64" else 8
    rows = ["    " + ", ".join(vals[i : i + per]) + "," for i in range(0, len(vals), per)]
    zig += [f"\npub const {name} = [{len(vals)}]{zig_ty}{{", *rows, "};"]
    metal += [f"\nconstant {metal_ty} {name}[{len(vals)}] = {{", *rows, "};"]
(root / "src/iq_tables.zig").write_text("\n".join(zig) + "\n")
(root / "src/metal/iq_tables.h").write_text("\n".join(metal) + "\n")
